// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject1
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject1.4bf46ae7-6aae-4b00-b995-3d739a52ad30";
        public const string Name = "VSIXProject1";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Leyla Büchel";
        public const string Tags = "";
    }
}
