// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SimpleVSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSimpleVSIXPackageString = "7ef4a2de-4035-48c3-b273-4195d0f1186b";
        public static Guid guidSimpleVSIXPackage = new Guid(guidSimpleVSIXPackageString);

        public const string guidSimpleVSIXPackageCmdSetString = "7a9fcb09-91b7-4b18-acf2-7a320e74d4ff";
        public static Guid guidSimpleVSIXPackageCmdSet = new Guid(guidSimpleVSIXPackageCmdSetString);

        public const string guidImagesString = "bace7fec-7f13-4f48-99e1-252e65010f80";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "004b13d7-a571-44c0-9dd3-74fa608c2058";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MyMenuItem = 0x1021;
        public const int MySubMenuGroup = 0x1022;
        public const int Command1Id = 0x0100;
        public const int cmdidBrowse = 0x1023;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}